import os
import sys; sys.path.append('/opt/jlab_software/2.3/scons_bm')

#from util import scanFiles

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples

env.Command('ftof-nim.pdf', 'ftof-nim.tex', "latex $SOURCE > /dev/null; latex $SOURCE > /dev/null; latex $SOURCE ; dvipdfm ftof-nim.dvi")
#cleans = scanFiles('.', accept=["ftof-nim.*", "*.aux"], reject=[".tex"])
#Clean('ftof-nim.pdf', cleans)
