import os
import sys; sys.path.append('/opt/jlab_software/2.3/scons_bm')

from util import scanFiles

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples

env.Command('beamline_nim.pdf', 'beamline_nim.tex', "pdflatex $SOURCE; bibtex beamline_nim ; pdflatex $SOURCE; pdflatex $SOURCE")
cleans = scanFiles('.', accept=["beamline_nim.*", "*.aux"], reject=[".tex"])
Clean('simulations.pdf', cleans)
