import os

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples

env.Command('beamline_nim.pdf', 'beamline_nim.tex', "latex $SOURCE > /dev/null; latex $SOURCE > /dev/null; latex $SOURCE ; dvipdfm beamline_nim.dvi")
