import os
import sys; sys.path.append('/opt/jlab_software/2.3/scons_bm')

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples

env.Command('ctof-nim.pdf', 'ctof-nim.tex', "latex $SOURCE > /dev/null; latex $SOURCE > /dev/null; latex $SOURCE ; dvipdfm ctof-nim.dvi")
