import os

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples

env.Command('dc12_nim.pdf', 'dc12_nim.tex', "latex $SOURCE > /dev/null; latex $SOURCE > /dev/null; latex $SOURCE ; dvipdfm dc12_nim.dvi")
