import os

env = Environment(PDFLATEXFLAGS = "-halt-on-error")  # stops log where error occurs
env['ENV']['max_print_line']='1048576'               # log output does not break single lines into multiples
env.Command('ltcc.pdf', 'ltcc.tex', "pdflatex $SOURCE > /dev/null; bibtex ltcc ; pdflatex $SOURCE > /dev/null; pdflatex $SOURCE")
cleans = scanFiles('.', accept=["ltcc*", "*.aux"], reject=[".tex"])
